// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLzN9Fh49FN6A9BiTCOziD-twdesnZZ0s',
    appId: '1:196062022855:web:8d5da9597ee5e4561582e2',
    messagingSenderId: '196062022855',
    projectId: 'whats-movie-flutter-app',
    authDomain: 'whats-movie-flutter-app.firebaseapp.com',
    storageBucket: 'whats-movie-flutter-app.appspot.com',
    measurementId: 'G-P91EQ13583',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdSJq415GmAefd7RGjvvAt0yCsm9P-VRY',
    appId: '1:196062022855:ios:e71177edc5c17d991582e2',
    messagingSenderId: '196062022855',
    projectId: 'whats-movie-flutter-app',
    storageBucket: 'whats-movie-flutter-app.appspot.com',
    iosBundleId: 'com.example.whatsMovieFlutterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBdSJq415GmAefd7RGjvvAt0yCsm9P-VRY',
    appId: '1:196062022855:ios:e71177edc5c17d991582e2',
    messagingSenderId: '196062022855',
    projectId: 'whats-movie-flutter-app',
    storageBucket: 'whats-movie-flutter-app.appspot.com',
    iosBundleId: 'com.example.whatsMovieFlutterApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCLzN9Fh49FN6A9BiTCOziD-twdesnZZ0s',
    appId: '1:196062022855:web:01b5f2e598e386651582e2',
    messagingSenderId: '196062022855',
    projectId: 'whats-movie-flutter-app',
    authDomain: 'whats-movie-flutter-app.firebaseapp.com',
    storageBucket: 'whats-movie-flutter-app.appspot.com',
    measurementId: 'G-ZNEYWMMLPQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC49sG_pus58-F9kq1GndGEgRnLMLZVKc0',
    appId: '1:196062022855:android:6a8d4b7000b453081582e2',
    messagingSenderId: '196062022855',
    projectId: 'whats-movie-flutter-app',
    storageBucket: 'whats-movie-flutter-app.appspot.com',
  );

}